name: Kits
version: '${project.version}'
main: me.cole.kitsplugin.Kits
api-version: '1.20'
commands:
  level:
    description: Testing
  setxp:
    description: Testing
  checklevel:
    description: Testing
