name: Kits
version: '1.0'
main: me.cole.kitsplugin.Kits
api-version: '1.20'
commands:
  title:
    description: Testing
  level:
    description: Testing
  setlevel:
    description: Testing
  setxp:
    description: Testing
  checklevel:
    description: Testing
